name: clang-tidy

on:
  pull_request:
    branches: '**'
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory $GITHUB_WORKSPACE/build

    - name: test
      working-directory: $GITHUB_WORKSPACE/build
      run: pwd && ls 

    - name: Execute CMAKE
      shell: bash
      working-directory: $GITHUB_WORKSPACE/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Execute clang-tidy
      shell: bash
      working-directory: $GITHUB_WORKSPACE
      run: clang-tidy -p=./$BUILD/ -warnings-as-errors="*" -checks="-*,clang-analyzer-*,bugprone-*,hicpp-*,modernize-*,openmp-*" nsa.cpp
