name: clang-tidy

on:
  pull_request:
    branches: '**'
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory $GITHUB_WORKSPACE/build

    - name: Execute CMAKE
      shell: bash
      working-directory: ./build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Update and Install clang-tidy
      shell: bash
      run: sudo apt update -y && sudo apt install -y clang-tidy
      
    - name: Execute clang-tidy
      shell: bash
      run: clang-tidy -p=./build -warnings-as-errors="*" -checks="-*,clang-analyzer-*,bugprone-*,hicpp-*,modernize-*,openmp-*" ./src/nsa.cpp
