name: valgrind

on:
  pull_request:
    branches: "**"
  push:
    branches: "**"

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependecy
        shell: bash
        run: sudo apt update -y && sudo apt -y install valgrind

      - name: Create Build Environment
        run: mkdir build

      - name: Configure CMake
        shell: bash
        working-directory: ./build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        shell: bash
        working-directory: ./build
        run: cmake --build . --config $BUILD_TYPE

      - name: Execute Valgrind
        shell: bash
        working-directory: ./data
        run: valgrind --error-exitcode=99 --leak-check=full ../build/nsa dataset.conf
